version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nadpos_db
    restart: always
    environment:
      POSTGRES_USER: nadpos_root
      POSTGRES_PASSWORD: SecretPassword123!
      POSTGRES_DB: nadpos_cloud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
